<a href="https://colab.research.google.com/github/ShubhamJadhav03/DeepLearning/blob/main/Bert_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [4]:
import tensorflow_hub as hub

In [2]:
import tensorflow_text as text

In [3]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [5]:
bert_preproces_model = hub.KerasLayer(preprocess_url)

In [7]:
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preproces_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [9]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [11]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

101 --> CLS token

102 --> SEP token

In [12]:
bert_model = hub.KerasLayer(encoder_url)

In [13]:
bert_results = bert_model(text_preprocessed)

In [14]:
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [15]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292055,  0.08567822,  0.14476837, ..., -0.09677067,
          0.08722132,  0.07711101],
        [ 0.1783942 , -0.1900609 ,  0.50349414, ..., -0.05869763,
          0.32717133, -0.15578507],
        [ 0.18701527, -0.43388727, -0.48875186, ..., -0.15502739,
          0.00145194, -0.24470969],
        ...,
        [ 0.12083019,  0.12884212,  0.46453553, ...,  0.07375549,
          0.17441961,  0.16522165],
        [ 0.07967892, -0.01190671,  0.50225407, ...,  0.13777724,
          0.21002257,  0.00624547],
        [-0.07212661, -0.28303477,  0.5903341 , ...,  0.47551954,
          0.1666847 , -0.08920329]],

       [[-0.0790057 ,  0.3633508 , -0.21101609, ..., -0.17183742,
          0.16299754,  0.6724269 ],
        [ 0.27883506,  0.43716297, -0.35764715, ..., -0.04463629,
          0.38315165,  0.5887988 ],
        [ 1.2037677 ,  1.0727019 ,  0.4840876 , ...,  0.24920993,
          0.4073093 ,  0.404818  ],
        ...,

In [16]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.791774  , -0.21411909,  0.49769595, ...,  0.24465248,
        -0.47334474,  0.81758696],
       [-0.917123  , -0.4793516 , -0.7865695 , ..., -0.6175171 ,
        -0.71026856,  0.9218428 ]], dtype=float32)>